#!/bin/bash
#
#
# This file is sourced automatically by xsh if the current shell is `bash`.
#
# It should merely register the modules to be loaded for each runcom:
# env, login, interactive and logout.
# The order in which the modules are registered defines the order in which
# they will be loaded. Try `xsh help` for more information.
#
# Do not edit this file


# Load other init_*.bash files
xsh__load ()
{
  # Lookup for generic files
  local user=$(id -u -n)
  local hostname=$(hostname)

  # Lookup for user files
  files1=$( ls -1 $HOME/.config/shell/bash/init_${hostname}.bash )
  files2=$( ls -1 $HOME/.config/shell/bash/init_${user}.bash )
  for file in $files $files1 $files2; do
    . $file
  done

}

xsh__load 


