#!/bin/bash


install_xsh ()
{
  git clone https://github.com/sgleizes/xsh ~/.config/xsh
  . "${XSH_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/xsh}/xsh.sh"
  xsh bootstrap
}

install_yadm_dist ()
{
  local dest_bin="$HOME/.local/bin/yadm"
  curl -fLo "$dest_bin" https://github.com/TheLocehiliosan/yadm/raw/master/yadm \
    && chmod a+x "$dest_bin"
}

install_yadm_dev ()
{
  local dest_git="$HOME/.local/shell/yadm"
  local dest_bin="$HOME/.local/bin/yadm"
  git clone https://github.com/TheLocehiliosan/yadm.git "$dest_git"
  ln -s "$dest_git/yadm" "$dest_bin"
}

ensure_dirs ()
{
  mkdir -p $HOME/.local/{share,bin}
}

echo "Executing debootstraping !"
ensure_dirs
install_yadm
#install_ellipsis
#install_xsh
