#!/bin/bash
#
## Test bootstrap:
# /upstream/dotfiles-generic/.config/yadm/bootstrap
#


git_clone_pull ()
{
  local dest=$1
  local repo=$2

  if [ -d "$dest" ]; then
    git -C "$dest" pull
  else
    git clone "$repo" "$dest"
  fi
}

create_symlink ()
{
  local src=$1
  local dest=$2

  if [ ! -L "$dest" ]; then
    ln -s "$src" "$dest"
  fi
}


install_xsh_dev ()
{

  local repo="https://github.com/sgleizes/xsh"
  local dest_git="$HOME/.local/shell/xsh"
  local dest_bin="$HOME/.config/xsh"

  git_clone_pull "$dest_git"  "$repo"
  create_symlink "$dest_git" "$dest_bin"

  . "${XSH_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/xsh}/xsh.sh"
  local shell=posix
  if command -v bash >&/dev/null; then
    shell=bash
  elif command -v zsh >&/dev/null; then
    shell=zsh
  fi
  xsh -s $shell bootstrap 
}

install_yadm_dist ()
{
  local dest_bin="$HOME/.local/bin/yadm"
  curl -fLo "$dest_bin" https://github.com/TheLocehiliosan/yadm/raw/master/yadm \
    && chmod a+x "$dest_bin"
}

install_yadm_dev ()
{
  local dest_git="$HOME/.local/shell/yadm"
  local dest_bin="$HOME/.local/bin/yadm"
  git clone https://github.com/TheLocehiliosan/yadm.git "$dest_git"
  ln -s "$dest_git/yadm" "$dest_bin"
}

prepare_install ()
{
  mkdir -p $HOME/.local/{share,bin,lib}
  export PATH="$HOME/bin:$HOME/.local/bin:$PATH"

  # XDG paths:
  # $HOME/.config # $XDG_CONFIG_HOME
  # $HOME/.local/share # $XDG_DATA_HOME
  # PATH+ =  $HOME/.local/bin
  # $HOME/.local/state  # $XDG_STATE_HOME
  # $HOME/.cache # $XDG_CACHE_HOME
  # # Optonal: /run/user/1000 # $XDG_RUNTIME_DIR
}

echo "Executing debootstraping !"
prepare_install

#command -v yadm >&/dev/null \
install_yadm_dist
install_xsh_dev
#install_ellipsis

>&2 echo "INFO: Home correctly installed. Please start new instance of your shell: $SHELL"

