
git_clone_pull ()
{
  local dest=$1
  local repo=$2

  if [ -d "$dest/.git" ]; then
    git -C "$dest" pull --ff-only
  else
    git clone "$repo" "$dest"
  fi
}

create_shim ()
{
  local src=$1
  local dest=$2

  cat > $dest <<EOF
#!/bin/sh
# Autogenerated shim for asdf
exec $src \$@
EOF
  chmod +x "$dest"
}


xsh_install_basher_git ()
{

  local repo="https://github.com/basherpm/basher.git"
  local dest_git="$HOME/.local/shell/basher"
  local dest_bin="$HOME/.local/bin/basher"


  #xsh load home_basher env
  git_clone_pull "$dest_git"  "$repo"
  create_shim "$dest_git/libexec/basher" "$dest_bin"

}


xsh_install_basher_git
>&2 echo "Basher has been installed"
