
git_clone_pull ()
{
  local dest=$1
  local repo=$2
  local ref=${3:-main}

  if [ ! -d "$dest/.git" ]; then
    git clone "$repo" "$dest" 
  fi

  git -C "$dest" checkout $ref
}

create_shim ()
{
  local src=$1
  local dest=$2

  cat > $dest <<EOF
#!/bin/sh
# Autogenerated shim for xsh
exec $src \$@
EOF
  chmod +x "$dest"
}


xsh_install_asdf_git ()
{
  local version=v0.11.3

  local repo="https://github.com/asdf-vm/asdf.git"
  local dest_git="$HOME/.local/shell/asdf"
  local dest_bin="$HOME/.local/bin/asdf"

  mkdir -p "$HOME/.local/shell/" "$HOME/.local/bin/"

  # DISABLE: advice.detachedHead
  git_clone_pull "$dest_git" "$repo" $version
  create_shim "$dest_git/bin/asdf" "$dest_bin"

}


xsh_install_asdf_git
>&2 echo "asdf has been installed"
