
git_clone_pull ()
{
  local dest=$1
  local repo=$2

  if [ -d "$dest/.git" ]; then
    git -C "$dest" pull --ff-only
  else
    git clone "$repo" "$dest"
  fi
}

create_shim ()
{
  local src=$1
  local dest=$2

  cat > $dest <<EOF
#!/bin/sh
# Autogenerated shim for xsh
exec $src \$@
EOF
  chmod +x "$dest"
}


xsh_install_ellipsis_git ()
{

  local repo="https://github.com/ellipsis/ellipsis"
  local dest_git="$HOME/.local/shell/ellipsis"
  local dest_bin="$HOME/.local/bin/ellipsis"

  mkdir -p "$HOME/.local/shell/" "$HOME/.local/bin/"

  deps="bash curl git"
  for dep in $deps; do
      hash $dep 2>/dev/null || { echo >&2 "ellipsis requires $dep to be installed."; exit 1; }
  done

  xsh load home_ellipsis interactive

  git_clone_pull "$dest_git"  "$repo"
  create_shim "$dest_git/bin/ellipsis" "$dest_bin"

}


xsh_install_ellipsis_git
>&2 echo "Ellipsis has been installed"
